In [1]:
import pandas as pd

In [2]:
world_gdp = pd.read_csv('../data/country-GDP-2017.csv',encoding = "ISO-8859-1", names = ['Country', 'Country Code', 'GDP'], skiprows = 1)
world_gdp.head(1)

  Country Country Code           GDP
0   Aruba          ABW  2.081530e+10

In [3]:
# world_gdp['Country Name']

In [4]:
world_happiness = pd.read_csv('../data/world_happiness_2017.csv')
world_happiness.head(1)

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027

In [6]:
merged_df = pd.merge(world_gdp, world_happiness, on = ['Country', 'Country'])
merged_df.head()

,Country,Country Code,GDP,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Afghanistan,AFG,1.240000e+11,141,3.794,3.873661,3.714338,0.401477,0.581543,0.180747,0.106180,0.311871,0.061158,2.150801
1,Angola,AGO,1.303935e+10,140,3.795,3.951642,3.638358,0.858428,1.104412,0.049869,0.000000,0.097926,0.069720,1.614482
2,Albania,ALB,3.012914e+09,109,4.644,4.752464,4.535536,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,1.490442
3,United Arab Emirates,ARE,6.380000e+11,21,6.648,6.722047,6.573952,1.626343,1.266410,0.726798,0.608345,0.360942,0.324490,1.734704
4,Argentina,ARG,1.153659e+10,24,6.599,6.690085,6.507915,1.185295,1.440451,0.695137,0.494519,0.109457,0.059740,2.614005

In [7]:
merged_df.to_csv('../data/happiness_and_gdp.csv')

In [8]:
world_gdp = pd.read_csv('../data/country-GDP-2017.csv',encoding = "ISO-8859-1", names = ['Country', 'Country Code', 'GDP'], skiprows = 1)
world_happiness = pd.read_csv('../data/world_happiness_2017.csv')
merged_df = pd.merge(world_gdp, world_happiness, on = ['Country', 'Country'])
merged_df.head()

,Country,Country Code,GDP,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Afghanistan,AFG,1.240000e+11,141,3.794,3.873661,3.714338,0.401477,0.581543,0.180747,0.106180,0.311871,0.061158,2.150801
1,Angola,AGO,1.303935e+10,140,3.795,3.951642,3.638358,0.858428,1.104412,0.049869,0.000000,0.097926,0.069720,1.614482
2,Albania,ALB,3.012914e+09,109,4.644,4.752464,4.535536,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,1.490442
3,United Arab Emirates,ARE,6.380000e+11,21,6.648,6.722047,6.573952,1.626343,1.266410,0.726798,0.608345,0.360942,0.324490,1.734704
4,Argentina,ARG,1.153659e+10,24,6.599,6.690085,6.507915,1.185295,1.440451,0.695137,0.494519,0.109457,0.059740,2.614005